[tool.poetry]
name = "yakusoku"
version = "0.1.0"
description = ""
authors = ["Ricky8955555 <rkmiao@duck.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25.1"
aiohttp = "^3.8.4"
graphviz = "^0.20.1"
pydantic-yaml = "^1.1.1"
sqlmodel = "^0.0.8"
pydantic = "^1.10.12"
aiofile = "^3.8.7"
cashews = "^6.2.0"
aiosqlite = "^0.19.0"
alembic = "^1.11.2"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.316"
pyproject-flake8 = "^6.0.0.post1"
black = "^23.7.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUntypedFunctionDecorator = false
exclude = ["alembic/versions"]

[tool.black]
line-length = 100
exclude = "alembic/versions"

[tool.flake8]
max-line-length = 100
exclude = "alembic/versions"

[tool.isort]
line_length = 100
