[tool.poetry]
name = "yakusoku"
version = "0.1.0"
description = ""
authors = ["Ricky8955555 <rkmiao@duck.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^2.25.1"
sqlitedict = "^2.1.0"
aiohttp = "^3.8.4"
graphviz = "^0.20.1"
pydantic = "^2.1.1"
pydantic-yaml = "^1.1.1"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.316"
pyproject-flake8 = "^6.0.0.post1"
black = "^23.7.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownMemberType = false

[tool.black]
line-length = 100

[tool.flake8]
max-line-length = 100

[tool.isort]
line_length = 100
