[tool.poetry]
name = "yakusoku"
version = "0.1.0"
description = ""
authors = ["Ricky8955555 <rkmiao@duck.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0"


[tool.poetry.group.bot.dependencies]
aiogram = "^2.25.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
