[tool.poetry]
name = "yakusoku"
version = "0.1.0"
description = ""
authors = ["Ricky8955555 <rkmiao@duck.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
