"""greeting

Revision ID: 18729c4e3e0b
Revises: d4739ea74551
Create Date: 2023-12-09 10:26:34.291984

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '18729c4e3e0b'
down_revision: Union[str, None] = 'd4739ea74551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetingdata',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greetingdata')
    # ### end Alembic commands ###
