"""switch

Revision ID: 3203bfca7b48
Revises: 5ed1e1a53723
Create Date: 2024-03-17 13:19:47.170898

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3203bfca7b48'
down_revision: Union[str, None] = '5ed1e1a53723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('switchconfig',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group', 'module')
    )
    op.drop_table('greetingconfig')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetingconfig',
    sa.Column('group', sa.INTEGER(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('group')
    )
    op.drop_table('switchconfig')
    # ### end Alembic commands ###
