"""waifu data rename forced to restricted

Revision ID: 5277c5ec5067
Revises: bd57e7c3c941
Create Date: 2023-12-11 10:50:38.731218

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5277c5ec5067'
down_revision: Union[str, None] = 'bd57e7c3c941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waifudata', schema=None) as batch_op:
        batch_op.alter_column('forced', nullable=False, new_column_name='restricted')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waifudata', schema=None) as batch_op:
        batch_op.alter_column('restricted', nullable=False, new_column_name="forced")

    # ### end Alembic commands ###
