"""greeting group switch

Revision ID: 5ed1e1a53723
Revises: 5277c5ec5067
Create Date: 2024-01-30 21:17:01.952474

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5ed1e1a53723'
down_revision: Union[str, None] = '5277c5ec5067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetingconfig',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greetingconfig')
    # ### end Alembic commands ###
