"""greeting switch

Revision ID: bd57e7c3c941
Revises: 18729c4e3e0b
Create Date: 2023-12-10 09:00:10.037531

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'bd57e7c3c941'
down_revision: Union[str, None] = '18729c4e3e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greetingdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default="1"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('greetingdata', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
