"""initial

Revision ID: d4739ea74551
Revises: 
Create Date: 2023-08-13 21:28:28.952615

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd4739ea74551'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupdata',
    sa.Column('members', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdata',
    sa.Column('usernames', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waifuconfig',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('mentionable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user')
    )
    op.create_table('waifudata',
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=False),
    sa.Column('waifu', sa.Integer(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('forced', sa.Boolean(), nullable=False),
    sa.Column('rarity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('group', 'member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waifudata')
    op.drop_table('waifuconfig')
    op.drop_table('userdata')
    op.drop_table('groupdata')
    # ### end Alembic commands ###
